//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevPlugin.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DevPlugin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;configuration&gt;
        ///    &lt;configSections&gt;
        ///    &lt;/configSections&gt;
        ///&lt;startup&gt;&lt;supportedRuntime version=&quot;v4.0&quot; sku=&quot;.NETFramework,Version=v4.7.2&quot;/&gt;&lt;/startup&gt;&lt;/configuration&gt;
        ///.
        /// </summary>
        internal static string app {
            get {
                return ResourceManager.GetString("app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [Root]
        ///AppName=SimplePlugin
        ///Key=AMAAMAClwCmrp/8PrcmYWm2pqooirjD6zroEQ7RRumq+VFu/GBG8ZEIu6PqnxfU3lRblig0DAAEAAQ==
        ///Version=1.2.3
        ///PetrelVersion=2021.2(64-bit).
        /// </summary>
        internal static string AppInfo {
            get {
                return ResourceManager.GetString("AppInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на D:\svn\svn_kz\Projects\PetrelPluginGenerator\soft\bin\PetrelPluginBuilder.exe &quot;%CD%&quot;
        ///pause.
        /// </summary>
        internal static string build_plugin {
            get {
                return ResourceManager.GetString("build_plugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Fractures_key {
            get {
                object obj = ResourceManager.GetObject("Fractures_key", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на using System;
        ///using Slb.Ocean.Core;
        ///using Slb.Ocean.Petrel;
        ///using Slb.Ocean.Petrel.UI;
        ///using Slb.Ocean.Petrel.Workflow;
        ///using TCG.TimalLicensing;
        ///
        ///namespace TCG.SimplePlugin
        ///{
        ///    /// &lt;summary&gt;
        ///    /// This class will control the lifecycle of the Module.
        ///    /// The order of the methods are the same as the calling order.
        ///    /// &lt;/summary&gt;
        ///	public class Module : IModule
        ///	{
        ///		public Module()
        ///		{
        ///			//
        ///			// TODO: Add constructor logic here
        ///			//
        ///		}
        ///
        ///		#region IModule Members
        ///
        ///		/// &lt; [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Module {
            get {
                return ResourceManager.GetString("Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] newkey {
            get {
                object obj = ResourceManager.GetObject("newkey", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на using System;
        ///using System.Collections.Generic;
        ///
        ///using Slb.Ocean.Core;
        ///
        ///namespace TCG.SimplePlugin
        ///{
        ///    public class Plugin : Slb.Ocean.Core.Plugin
        ///    {
        ///        public override string AppVersion
        ///        {
        ///            get { return &quot;1.2.3&quot;; }
        ///        }
        ///
        ///        public override string Author
        ///        {
        ///            get { return &quot;Timal Consulting Group&quot;; }
        ///        }
        ///
        ///        public override string Contact
        ///        {
        ///            get { return &quot;plugins@timal.kz&quot;; }
        ///        }
        ///
        ///        public  [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Plugin {
            get {
                return ResourceManager.GetString("Plugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;InstalledPlugins xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///  &lt;Plugin&gt;
        ///    &lt;Name&gt;TCG.SimplePlugin&lt;/Name&gt;
        ///    &lt;Contact&gt;plugins@timal.kz&lt;/Contact&gt;
        ///    &lt;PluginTypeName&gt;TCG.SimplePlugin.Plugin, TCG.SimplePlugin, Version=1.0.3.0, Culture=neutral, PublicKeyToken=9de9635fa700ae8a&lt;/PluginTypeName&gt;
        ///    &lt;PluginUri&gt;http://www.timal.kz/&lt;/PluginUri&gt;
        ///    &lt;PluginId&gt;://TCG.SimplePlugin.Plugin/1.0.3.0&lt;/PluginId&gt;
        ///    &lt;Tru [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string plugin1 {
            get {
                return ResourceManager.GetString("plugin1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] TCG_SimplePlugin {
            get {
                object obj = ResourceManager.GetObject("TCG_SimplePlugin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Project ToolsVersion=&quot;4.0&quot; xmlns=&quot;http://schemas.microsoft.com/developer/msbuild/2003&quot;&gt;
        ///  &lt;PropertyGroup Condition=&quot;&apos;$(Configuration)|$(Platform)&apos; == &apos;Debug|AnyCPU&apos;&quot;&gt;
        ///    &lt;StartAction&gt;Program&lt;/StartAction&gt;
        ///    &lt;StartProgram&gt;c:\program files\schlumberger\Petrel 2021\petrel.exe&lt;/StartProgram&gt;
        ///    &lt;StartWorkingDirectory&gt;c:\program files\schlumberger\Petrel 2021\&lt;/StartWorkingDirectory&gt;
        ///  &lt;/PropertyGroup&gt;
        ///  &lt;PropertyGroup&gt;
        ///    &lt;ReferencePath&gt;C:\Program Files\Schlu [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string TCG_SimplePlugin_csproj {
            get {
                return ResourceManager.GetString("TCG_SimplePlugin_csproj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Project ToolsVersion=&quot;12.0&quot; DefaultTargets=&quot;Build&quot; xmlns=&quot;http://schemas.microsoft.com/developer/msbuild/2003&quot;&gt;
        ///  &lt;PropertyGroup&gt;
        ///    &lt;!--ProjectType:Plugin--&gt;
        ///    &lt;Configuration Condition=&quot; &apos;$(Configuration)&apos; == &apos;&apos; &quot;&gt;Debug&lt;/Configuration&gt;
        ///    &lt;Platform Condition=&quot; &apos;$(Platform)&apos; == &apos;&apos; &quot;&gt;AnyCPU&lt;/Platform&gt;
        ///    &lt;ProductVersion&gt;9.0.30729&lt;/ProductVersion&gt;
        ///    &lt;SchemaVersion&gt;2.0&lt;/SchemaVersion&gt;
        ///    &lt;ProjectGuid&gt;{034805E2-9B80-4F18-930B-0E789C4B9A8C}&lt;/ProjectGuid&gt;
        ///  [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string TCG_SimplePlugin1 {
            get {
                return ResourceManager.GetString("TCG_SimplePlugin1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на using System;
        ///
        ///using Slb.Ocean.Core;
        ///using Slb.Ocean.Petrel;
        ///using Slb.Ocean.Petrel.UI;
        ///using Slb.Ocean.Petrel.Workflow;
        ///using TCG.TimalLicensing;
        ///using Timal.Toolbox.Misc;
        ///
        ///namespace TCG.SimplePlugin
        ///{
        ///    /// &lt;summary&gt;
        ///    /// This class contains all the methods and subclasses of the Workstep1.
        ///    /// Worksteps are displayed in the workflow editor.
        ///    /// &lt;/summary&gt;
        ///	class Workstep1 : Workstep&lt;Workstep1.Arguments&gt;, IExecutorSource, IAppearance, IDescriptionSource
        ///	{
        ///		#region Overridden [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Workstep1 {
            get {
                return ResourceManager.GetString("Workstep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на using Slb.Ocean.Core;
        ///using Slb.Ocean.Petrel.Workflow;
        ///using Slb.Ocean.Units;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Windows.Forms;
        ///using System.Linq;
        ///
        ///namespace TCG.SimplePlugin
        ///{
        ///    /// &lt;summary&gt;
        ///    /// This class is the user interface which forms the focus for the capabilities offered by the process.  
        ///    /// This often includes UI to set up arguments and interactively run a batch part expressed as a workstep.
        ///    /// &lt;/summary&gt;
        ///    partial class Workstep1UI : UserC [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Workstep1UI {
            get {
                return ResourceManager.GetString("Workstep1UI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на namespace TCG.SimplePlugin
        ///{
        ///    partial class Workstep1UI
        ///    {
        ///        /// &lt;summary&gt; 
        ///        /// Required designer variable.
        ///        /// &lt;/summary&gt;
        ///        private System.ComponentModel.IContainer components = null;
        ///
        ///        /// &lt;summary&gt; 
        ///        /// Clean up any resources being used.
        ///        /// &lt;/summary&gt;
        ///        /// &lt;param name=&quot;disposing&quot;&gt;true if managed resources should be disposed; otherwise, false.&lt;/param&gt;
        ///        protected override void Dispose(bool disposing)
        ///        {
        ///           [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Workstep1UI_Designer {
            get {
                return ResourceManager.GetString("Workstep1UI_Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;root&gt;
        ///  &lt;!-- 
        ///    Microsoft ResX Schema 
        ///    
        ///    Version 2.0
        ///    
        ///    The primary goals of this format is to allow a simple XML format 
        ///    that is mostly human readable. The generation and parsing of the 
        ///    various data types are done through the TypeConverter classes 
        ///    associated with the data types.
        ///    
        ///    Example:
        ///    
        ///    ... ado.net/XML headers &amp; schema ...
        ///    &lt;resheader name=&quot;resmimetype&quot;&gt;text/microsoft-resx&lt;/resheader&gt;
        ///    &lt;resheader n [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Workstep1UI1 {
            get {
                return ResourceManager.GetString("Workstep1UI1", resourceCulture);
            }
        }
    }
}
